package vip.vmansus.cloud.vcloud.model;

public class FileStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_store.file_store_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer fileStoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_store.user_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_store.current_size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer currentSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_store.max_size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer maxSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_store.permission
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.file_store_id
     *
     * @return the value of file_store.file_store_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getFileStoreId() {
        return fileStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.file_store_id
     *
     * @param fileStoreId the value for file_store.file_store_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setFileStoreId(Integer fileStoreId) {
        this.fileStoreId = fileStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.user_id
     *
     * @return the value of file_store.user_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.user_id
     *
     * @param userId the value for file_store.user_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.current_size
     *
     * @return the value of file_store.current_size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getCurrentSize() {
        return currentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.current_size
     *
     * @param currentSize the value for file_store.current_size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setCurrentSize(Integer currentSize) {
        this.currentSize = currentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.max_size
     *
     * @return the value of file_store.max_size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getMaxSize() {
        return maxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.max_size
     *
     * @param maxSize the value for file_store.max_size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setMaxSize(Integer maxSize) {
        this.maxSize = maxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.permission
     *
     * @return the value of file_store.permission
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.permission
     *
     * @param permission the value for file_store.permission
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
}