package vip.vmansus.cloud.vcloud.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileFolderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public FileFolderExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileFolderIdIsNull() {
            addCriterion("file_folder_id is null");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdIsNotNull() {
            addCriterion("file_folder_id is not null");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdEqualTo(Integer value) {
            addCriterion("file_folder_id =", value, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdNotEqualTo(Integer value) {
            addCriterion("file_folder_id <>", value, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdGreaterThan(Integer value) {
            addCriterion("file_folder_id >", value, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("file_folder_id >=", value, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdLessThan(Integer value) {
            addCriterion("file_folder_id <", value, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdLessThanOrEqualTo(Integer value) {
            addCriterion("file_folder_id <=", value, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdIn(List<Integer> values) {
            addCriterion("file_folder_id in", values, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdNotIn(List<Integer> values) {
            addCriterion("file_folder_id not in", values, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdBetween(Integer value1, Integer value2) {
            addCriterion("file_folder_id between", value1, value2, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("file_folder_id not between", value1, value2, "fileFolderId");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameIsNull() {
            addCriterion("file_folder_name is null");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameIsNotNull() {
            addCriterion("file_folder_name is not null");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameEqualTo(String value) {
            addCriterion("file_folder_name =", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameNotEqualTo(String value) {
            addCriterion("file_folder_name <>", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameGreaterThan(String value) {
            addCriterion("file_folder_name >", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameGreaterThanOrEqualTo(String value) {
            addCriterion("file_folder_name >=", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameLessThan(String value) {
            addCriterion("file_folder_name <", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameLessThanOrEqualTo(String value) {
            addCriterion("file_folder_name <=", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameLike(String value) {
            addCriterion("file_folder_name like", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameNotLike(String value) {
            addCriterion("file_folder_name not like", value, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameIn(List<String> values) {
            addCriterion("file_folder_name in", values, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameNotIn(List<String> values) {
            addCriterion("file_folder_name not in", values, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameBetween(String value1, String value2) {
            addCriterion("file_folder_name between", value1, value2, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andFileFolderNameNotBetween(String value1, String value2) {
            addCriterion("file_folder_name not between", value1, value2, "fileFolderName");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIsNull() {
            addCriterion("parent_folder_id is null");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIsNotNull() {
            addCriterion("parent_folder_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdEqualTo(Integer value) {
            addCriterion("parent_folder_id =", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotEqualTo(Integer value) {
            addCriterion("parent_folder_id <>", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdGreaterThan(Integer value) {
            addCriterion("parent_folder_id >", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_folder_id >=", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLessThan(Integer value) {
            addCriterion("parent_folder_id <", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_folder_id <=", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIn(List<Integer> values) {
            addCriterion("parent_folder_id in", values, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotIn(List<Integer> values) {
            addCriterion("parent_folder_id not in", values, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_folder_id between", value1, value2, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_folder_id not between", value1, value2, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdIsNull() {
            addCriterion("file_store_id is null");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdIsNotNull() {
            addCriterion("file_store_id is not null");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdEqualTo(Integer value) {
            addCriterion("file_store_id =", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdNotEqualTo(Integer value) {
            addCriterion("file_store_id <>", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdGreaterThan(Integer value) {
            addCriterion("file_store_id >", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("file_store_id >=", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdLessThan(Integer value) {
            addCriterion("file_store_id <", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("file_store_id <=", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdIn(List<Integer> values) {
            addCriterion("file_store_id in", values, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdNotIn(List<Integer> values) {
            addCriterion("file_store_id not in", values, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("file_store_id between", value1, value2, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("file_store_id not between", value1, value2, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_folder
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 16 18:39:48 HKT 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_folder
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}