package vip.vmansus.cloud.vcloud.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MyFileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public MyFileExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMyFileIdIsNull() {
            addCriterion("my_file_id is null");
            return (Criteria) this;
        }

        public Criteria andMyFileIdIsNotNull() {
            addCriterion("my_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyFileIdEqualTo(Integer value) {
            addCriterion("my_file_id =", value, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdNotEqualTo(Integer value) {
            addCriterion("my_file_id <>", value, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdGreaterThan(Integer value) {
            addCriterion("my_file_id >", value, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("my_file_id >=", value, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdLessThan(Integer value) {
            addCriterion("my_file_id <", value, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("my_file_id <=", value, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdIn(List<Integer> values) {
            addCriterion("my_file_id in", values, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdNotIn(List<Integer> values) {
            addCriterion("my_file_id not in", values, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdBetween(Integer value1, Integer value2) {
            addCriterion("my_file_id between", value1, value2, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("my_file_id not between", value1, value2, "myFileId");
            return (Criteria) this;
        }

        public Criteria andMyFileNameIsNull() {
            addCriterion("my_file_name is null");
            return (Criteria) this;
        }

        public Criteria andMyFileNameIsNotNull() {
            addCriterion("my_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andMyFileNameEqualTo(String value) {
            addCriterion("my_file_name =", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameNotEqualTo(String value) {
            addCriterion("my_file_name <>", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameGreaterThan(String value) {
            addCriterion("my_file_name >", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("my_file_name >=", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameLessThan(String value) {
            addCriterion("my_file_name <", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameLessThanOrEqualTo(String value) {
            addCriterion("my_file_name <=", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameLike(String value) {
            addCriterion("my_file_name like", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameNotLike(String value) {
            addCriterion("my_file_name not like", value, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameIn(List<String> values) {
            addCriterion("my_file_name in", values, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameNotIn(List<String> values) {
            addCriterion("my_file_name not in", values, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameBetween(String value1, String value2) {
            addCriterion("my_file_name between", value1, value2, "myFileName");
            return (Criteria) this;
        }

        public Criteria andMyFileNameNotBetween(String value1, String value2) {
            addCriterion("my_file_name not between", value1, value2, "myFileName");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdIsNull() {
            addCriterion("file_store_id is null");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdIsNotNull() {
            addCriterion("file_store_id is not null");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdEqualTo(Integer value) {
            addCriterion("file_store_id =", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdNotEqualTo(Integer value) {
            addCriterion("file_store_id <>", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdGreaterThan(Integer value) {
            addCriterion("file_store_id >", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("file_store_id >=", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdLessThan(Integer value) {
            addCriterion("file_store_id <", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("file_store_id <=", value, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdIn(List<Integer> values) {
            addCriterion("file_store_id in", values, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdNotIn(List<Integer> values) {
            addCriterion("file_store_id not in", values, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("file_store_id between", value1, value2, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andFileStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("file_store_id not between", value1, value2, "fileStoreId");
            return (Criteria) this;
        }

        public Criteria andMyFilePathIsNull() {
            addCriterion("my_file_path is null");
            return (Criteria) this;
        }

        public Criteria andMyFilePathIsNotNull() {
            addCriterion("my_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andMyFilePathEqualTo(String value) {
            addCriterion("my_file_path =", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathNotEqualTo(String value) {
            addCriterion("my_file_path <>", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathGreaterThan(String value) {
            addCriterion("my_file_path >", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("my_file_path >=", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathLessThan(String value) {
            addCriterion("my_file_path <", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathLessThanOrEqualTo(String value) {
            addCriterion("my_file_path <=", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathLike(String value) {
            addCriterion("my_file_path like", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathNotLike(String value) {
            addCriterion("my_file_path not like", value, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathIn(List<String> values) {
            addCriterion("my_file_path in", values, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathNotIn(List<String> values) {
            addCriterion("my_file_path not in", values, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathBetween(String value1, String value2) {
            addCriterion("my_file_path between", value1, value2, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andMyFilePathNotBetween(String value1, String value2) {
            addCriterion("my_file_path not between", value1, value2, "myFilePath");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeIsNull() {
            addCriterion("download_time is null");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeIsNotNull() {
            addCriterion("download_time is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeEqualTo(Integer value) {
            addCriterion("download_time =", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeNotEqualTo(Integer value) {
            addCriterion("download_time <>", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeGreaterThan(Integer value) {
            addCriterion("download_time >", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("download_time >=", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeLessThan(Integer value) {
            addCriterion("download_time <", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeLessThanOrEqualTo(Integer value) {
            addCriterion("download_time <=", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeIn(List<Integer> values) {
            addCriterion("download_time in", values, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeNotIn(List<Integer> values) {
            addCriterion("download_time not in", values, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeBetween(Integer value1, Integer value2) {
            addCriterion("download_time between", value1, value2, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("download_time not between", value1, value2, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNull() {
            addCriterion("upload_time is null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNotNull() {
            addCriterion("upload_time is not null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeEqualTo(Date value) {
            addCriterion("upload_time =", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotEqualTo(Date value) {
            addCriterion("upload_time <>", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThan(Date value) {
            addCriterion("upload_time >", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upload_time >=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThan(Date value) {
            addCriterion("upload_time <", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("upload_time <=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIn(List<Date> values) {
            addCriterion("upload_time in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotIn(List<Date> values) {
            addCriterion("upload_time not in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeBetween(Date value1, Date value2) {
            addCriterion("upload_time between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("upload_time not between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIsNull() {
            addCriterion("parent_folder_id is null");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIsNotNull() {
            addCriterion("parent_folder_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdEqualTo(Integer value) {
            addCriterion("parent_folder_id =", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotEqualTo(Integer value) {
            addCriterion("parent_folder_id <>", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdGreaterThan(Integer value) {
            addCriterion("parent_folder_id >", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_folder_id >=", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLessThan(Integer value) {
            addCriterion("parent_folder_id <", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_folder_id <=", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIn(List<Integer> values) {
            addCriterion("parent_folder_id in", values, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotIn(List<Integer> values) {
            addCriterion("parent_folder_id not in", values, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_folder_id between", value1, value2, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_folder_id not between", value1, value2, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Integer value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Integer value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Integer value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Integer value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Integer value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Integer> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Integer> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Integer value1, Integer value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPostfixIsNull() {
            addCriterion("postfix is null");
            return (Criteria) this;
        }

        public Criteria andPostfixIsNotNull() {
            addCriterion("postfix is not null");
            return (Criteria) this;
        }

        public Criteria andPostfixEqualTo(String value) {
            addCriterion("postfix =", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixNotEqualTo(String value) {
            addCriterion("postfix <>", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixGreaterThan(String value) {
            addCriterion("postfix >", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixGreaterThanOrEqualTo(String value) {
            addCriterion("postfix >=", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixLessThan(String value) {
            addCriterion("postfix <", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixLessThanOrEqualTo(String value) {
            addCriterion("postfix <=", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixLike(String value) {
            addCriterion("postfix like", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixNotLike(String value) {
            addCriterion("postfix not like", value, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixIn(List<String> values) {
            addCriterion("postfix in", values, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixNotIn(List<String> values) {
            addCriterion("postfix not in", values, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixBetween(String value1, String value2) {
            addCriterion("postfix between", value1, value2, "postfix");
            return (Criteria) this;
        }

        public Criteria andPostfixNotBetween(String value1, String value2) {
            addCriterion("postfix not between", value1, value2, "postfix");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_file
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 16 18:39:48 HKT 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_file
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}