package vip.vmansus.cloud.vcloud.model;

import java.util.Date;

public class MyFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.my_file_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer myFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.my_file_name
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private String myFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.file_store_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer fileStoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.my_file_path
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private String myFilePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.download_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer downloadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.upload_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.parent_folder_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer parentFolderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.type
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_file.postfix
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private String postfix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.my_file_id
     *
     * @return the value of my_file.my_file_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getMyFileId() {
        return myFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.my_file_id
     *
     * @param myFileId the value for my_file.my_file_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setMyFileId(Integer myFileId) {
        this.myFileId = myFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.my_file_name
     *
     * @return the value of my_file.my_file_name
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getMyFileName() {
        return myFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.my_file_name
     *
     * @param myFileName the value for my_file.my_file_name
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setMyFileName(String myFileName) {
        this.myFileName = myFileName == null ? null : myFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.file_store_id
     *
     * @return the value of my_file.file_store_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getFileStoreId() {
        return fileStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.file_store_id
     *
     * @param fileStoreId the value for my_file.file_store_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setFileStoreId(Integer fileStoreId) {
        this.fileStoreId = fileStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.my_file_path
     *
     * @return the value of my_file.my_file_path
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getMyFilePath() {
        return myFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.my_file_path
     *
     * @param myFilePath the value for my_file.my_file_path
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setMyFilePath(String myFilePath) {
        this.myFilePath = myFilePath == null ? null : myFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.download_time
     *
     * @return the value of my_file.download_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getDownloadTime() {
        return downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.download_time
     *
     * @param downloadTime the value for my_file.download_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setDownloadTime(Integer downloadTime) {
        this.downloadTime = downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.upload_time
     *
     * @return the value of my_file.upload_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.upload_time
     *
     * @param uploadTime the value for my_file.upload_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.parent_folder_id
     *
     * @return the value of my_file.parent_folder_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getParentFolderId() {
        return parentFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.parent_folder_id
     *
     * @param parentFolderId the value for my_file.parent_folder_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setParentFolderId(Integer parentFolderId) {
        this.parentFolderId = parentFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.size
     *
     * @return the value of my_file.size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.size
     *
     * @param size the value for my_file.size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.type
     *
     * @return the value of my_file.type
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.type
     *
     * @param type the value for my_file.type
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_file.postfix
     *
     * @return the value of my_file.postfix
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getPostfix() {
        return postfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_file.postfix
     *
     * @param postfix the value for my_file.postfix
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setPostfix(String postfix) {
        this.postfix = postfix == null ? null : postfix.trim();
    }
}