package vip.vmansus.cloud.vcloud.model;

import java.util.Date;

public class TempFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.file_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.file_name
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.upload_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_file.file_path
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_file.file_id
     *
     * @return the value of temp_file.file_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_file.file_id
     *
     * @param fileId the value for temp_file.file_id
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_file.file_name
     *
     * @return the value of temp_file.file_name
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_file.file_name
     *
     * @param fileName the value for temp_file.file_name
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_file.size
     *
     * @return the value of temp_file.size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_file.size
     *
     * @param size the value for temp_file.size
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_file.upload_time
     *
     * @return the value of temp_file.upload_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_file.upload_time
     *
     * @param uploadTime the value for temp_file.upload_time
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_file.file_path
     *
     * @return the value of temp_file.file_path
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_file.file_path
     *
     * @param filePath the value for temp_file.file_path
     *
     * @mbg.generated Wed Sep 16 18:39:48 HKT 2020
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }
}